spring:
  datasource:
    sqlite:
      url: 'jdbc:sqlite::memory:'
      driver-class-name: org.sqlite.JDBC
      initialization-mode: always
    h2:
      url: 'jdbc:h2:mem:testdb'
      driver-class-name: org.h2.Driver
      username: sa
      password:
      initialization-mode: always