spring:
  datasource:
    url: jdbc:h2:mem:testdb # H2数据库，数据保存在内存中
    username: sa
    password:
    driverClassName: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:db/schema.sql # 初始化SQL语句
  h2:
    console:
      enabled: true # 开启H2控制台，通过http://localhost:8080/h2-console访问