logging:
  level:
    com:
      example:
        demo:
          mapper: debug
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  sql:
    init:
      schema-locations: 'classpath:db/schema.sql'
      data-locations: 'classpath:db/data.sql'
  data:
    redis:
      host: 192.168.1.144
      port: 6379
      database: 0
